#1 File struct & godot project
Blobson/break-a-leg pull request #1
Opened 2023-07-25 15:12 UTC by Svedmit

2023-07-25 15:21 UTC, Blobson commented
А где файловая структура-то?

2023-07-25 15:21 UTC, Blobson requested changes

2023-07-25 15:21 UTC, Blobson commented on icon.svg
Давайте эту иконку сразу удалим - IMHO она не нужна.

2023-07-25 15:21 UTC, Blobson commented on README.md
> +# FileStrDescription:
А это что за зверь?

2023-07-26 11:31 UTC, Blobson requested changes
Мне не нравится, что намешаны три схемы именования директорий:
- base_character
- TileMap
- HP_indicator
Давайте выберем одну snake_case или CamelCase и её будем применять не только для директорий, но и для именования файлов.

2023-07-26 16:03 UTC, Expert-3-line commented
А есть для базовых сцен статических и динамических препятствий место?

2023-07-26 16:04 UTC, VasyaLel commented
А есть для базовых сцен от статических и динамических препятствий место?

2023-07-26 20:04 UTC, Svedmit commented
> А есть для базовых сцен от статических и динамических препятствий место?

Да, в папке региона

2023-07-26 20:53 UTC, Blobson approved these changes

2023-07-26 20:53 UTC, Blobson commented on characters/Courier/animations/.geetkeep
`Courier`  > `courier`

2023-07-26 20:53 UTC, Blobson commented on utils/Camera/.geetkeep
`Camera` > `camera`

2023-07-26 20:53 UTC, Blobson commented on ui/main/phone_menu/Tasks/.geetkeep
`Tasks` > `tasks`

2023-07-27 07:22 UTC, VasyaLel approved these changes

2023-07-27 07:28 UTC, merged