#108 Streets list
Blobson/break-a-leg pull request #130
Opened 2023-09-08 14:35 UTC by Svedmit

2023-09-08 18:32 UTC, Bartolemy12 approved these changes

2023-09-09 16:58 UTC, Blobson requested changes

2023-09-09 16:58 UTC, Blobson commented on utils/task_generator/streest.txt
> +RESIDENTAL REGION:
Пусть в фале будет просто список улиц без заголовка `RESIDENTAL_REGION`.
Кажется этот файл должен лежать в `regions/residental_region/streets.txt`.

2023-09-09 18:56 UTC, Svedmit commented on utils/task_generator/streest.txt
> +RESIDENTAL REGION:
Исправлено

2023-09-09 18:57 UTC, Blobson approved these changes

2023-09-09 18:58 UTC, VasyaLel approved these changes

2023-09-09 18:58 UTC, merged