#96 Score indicator
Blobson/break-a-leg pull request #133
Opened 2023-09-12 19:22 UTC by Svedmit

2023-09-12 19:32 UTC, Blobson requested changes

2023-09-12 19:32 UTC, Blobson commented on utils/game_state/game_state.gd
> +signal score_updated(value: int)
Кажется, что должно быть три сигнала:
  -  `score_add(points: int)`
  -  `score_subtract(points: int)`
  -  `score_updated(old_score: int, new_score: int)`
  
Первые два `score_add` и `score_subtract` будут выстреливаться бонусами и препятствиями, чтобы менять общий счетчик. А общий счетчик уже должен выстреливать `score_updated`,  чтобы изменять UI.

2023-09-12 19:34 UTC, Blobson commented on utils/game_state/game_state.gd
> +signal score_updated(value: int)
Такая схема позволит делать интересные вещи, например ввести `score_multiplier` и делать бонусы, которые позволят удваивать/утраивать на несколько секунд все получаемые очки.

2023-09-12 19:35 UTC, Blobson requested changes

2023-09-12 19:35 UTC, Blobson commented on default_bus_layout.tres
> +bus/0/volume_db = -80.0
Это изменение можно откатить.

2023-09-12 19:37 UTC, Blobson requested changes

2023-09-12 19:37 UTC, Blobson commented on ui/level_ui/score_counter/score_counter.gd
> +@onready var score: int = 0
А мы не хотим счетчик очков привязать к уровню, на котором они заработаны?

2023-09-13 06:21 UTC, Svedmit commented on utils/game_state/game_state.gd
> +signal score_updated(value: int)
Что-то я не уверен на счет трех сигналов на один счетчик...

2023-09-13 06:21 UTC, Svedmit commented on default_bus_layout.tres
> +bus/0/volume_db = -80.0
Исправлю.

2023-09-13 06:22 UTC, Svedmit commented on ui/level_ui/score_counter/score_counter.gd
> +@onready var score: int = 0
В конце уровня когда будет оцениваться результат прохождения счетчик будет считываться и обнуляться.

2023-09-15 08:57 UTC, Bartolemy12 submitted a review, later dismissed

2023-09-16 09:13 UTC, Blobson approved these changes

2023-09-16 09:25 UTC, Bartolemy12 approved these changes

2023-09-16 09:26 UTC, merged