#114 Coin counter
Blobson/break-a-leg pull request #135
Opened 2023-09-17 20:07 UTC by Svedmit

2023-09-17 21:53 UTC, Bartolemy12 approved these changes

2023-09-19 20:44 UTC, Blobson requested changes

2023-09-19 20:44 UTC, Blobson commented on ui/common/coin_counter/textures/goldCoin1.png
Какая-то у нас прямо беда с именованием файлов. Вроде же договорились ;)

2023-09-20 07:05 UTC, Svedmit commented on ui/common/coin_counter/textures/goldCoin1.png
Это ж временные текстуры :)
Поправлю

2023-09-20 07:07 UTC, Blobson commented on ui/common/coin_counter/textures/goldCoin1.png
Нет ничего более постоянного...

2023-09-20 07:17 UTC, Svedmit commented on ui/common/coin_counter/textures/goldCoin1.png
Исправил, еще косяк нашел один ))

2023-09-20 08:03 UTC, Blobson requested changes

2023-09-20 08:03 UTC, Blobson commented on ui/common/coin_counter/coin_counter.gd
> +var coin_tween
А зачем глобальная переменная?

2023-09-20 08:03 UTC, Blobson commented on ui/common/coin_counter/coin_counter.gd
> +	coin_tween = create_tween() \
Тут было бы неплохо проверять, что твин уже работает и не запускать второй параллельно.

2023-09-23 07:55 UTC, VasyaLel reviewed
может все монетки в одной картинке загрузить, а использовать их по фреймам

2023-09-24 12:26 UTC, Blobson approved these changes

2023-09-25 07:54 UTC, VasyaLel approved these changes

2023-09-25 11:01 UTC, merged