#91 Индикатор количества энергии в виде 1-N точки (UI уровня)
Blobson/break-a-leg pull request #136
Opened 2023-09-20 22:51 UTC by Bartolemy12

2023-09-22 19:23 UTC, Blobson requested changes

2023-09-22 19:23 UTC, Blobson commented on ui/level_ui/energy_indicator/energy_indicator.gd
> +	Game.energy_reserve = 3
Нехорошо, что у нас `energy_reserve` хранится в `Game`. Количество энергии - это характеристика игрока и она должна быть в `character.gd`. Представь, что завтра мы захотим делать кооператив и на карте будут два игрока, что ты будешь делать с `Game.energy_reserve`?
В индикаторе же мы должны только обрабатывать сигнал `energy_updated(old_value: int, new_value: int)`.

2023-09-22 19:23 UTC, Blobson commented on characters/common/base_character/character.gd
> +		Game.player_sprint.emit()
Я не уверен что нам нужен сигнал `player_sprint`. Здесь лучше напрямую менять энергию и по её изменению должен автоматом эмиттится сигнал `energy_updated`

2023-09-22 19:23 UTC, Blobson commented on ui/level_ui/energy_indicator/energy_indicator.gd
> +@onready var first_pb = $EnergyTextureProgressBar1
Три - это хорошо, но надо, чтобы индикатор поддерживал переменное количество ячеек энергии. Посмотри как сделан HealthIndicator - там это реализовано.

2023-09-22 19:23 UTC, Blobson commented on ui/level_ui/energy_indicator/energy_indicator.gd
> +func _on_timer_timeout():
Метод ну очень похож на `_on_player_sprint` - подумай как можно выделить общую часть из этих методов в отдельный метод с параметрами и вызывать его в `_on_player_sprint` и в `_on_timer_timeout`.

2023-09-22 19:23 UTC, Blobson commented on ui/level_ui/energy_indicator/energy_indicator.gd
> +	if Game.energy_reserve == 3:
Все три части этого `if` выглядят как братья близнецы. Очевидно, можно сделать отдельный метод с параметрами и вызывать его во всех частях этого `if` с разными параметрами.

2023-09-22 19:23 UTC, Blobson commented on utils/game_state/game_state.gd
> +var energy_reserve: int = 3 :
Надо перенести в `character.gd` - я уже объяснил почему в другом комментарии.

2023-09-22 19:23 UTC, Blobson commented on utils/game_state/game_state.gd
> +signal player_sprint
Надо заменить на сигнал `energy_updated`.

2023-10-04 20:34 UTC, Blobson approved these changes

2023-10-04 20:34 UTC, Blobson commented on characters/common/base_character/character.gd
> +#		print('Energy ', energy)
Можно удалить

2023-10-06 08:44 UTC, Blobson approved these changes

2023-10-06 09:22 UTC, DemitrSpb approved these changes

2023-10-06 10:07 UTC, Blobson requested changes

2023-10-06 10:07 UTC, Blobson commented on characters/common/base_character/character.gd
> +	$EnergyRecoveryTimer.timeout.connect(_on_energy_recover)
Я же говорил что нельзя обращаться к узлам дерева в `_init()`

2023-10-06 14:40 UTC, Blobson approved these changes

2023-10-08 07:33 UTC, merged