#93 индикация здоровья
Blobson/break-a-leg pull request #137
Opened 2023-09-21 07:41 UTC by VasyaLel

2023-09-21 07:50 UTC, Blobson requested changes

2023-09-21 07:50 UTC, Blobson commented on ui/level_ui/health_indicator/heart.gd
> +	set(state):
Вот тут косяк, переименуй параметр в `new_state` иначе непонятно что ты меняешь дальше в `state = State.FULL`.

2023-09-21 07:52 UTC, Blobson requested changes

2023-09-21 07:52 UTC, Blobson commented on ui/level_ui/health_indicator/heart.gd
> +			state = State.FULL
Ну и эту строчку можно будет вынести в конец после `if` и сделать такой `state = new_state`

2023-09-21 16:15 UTC, VasyaLel commented on ui/level_ui/health_indicator/heart.gd
> +	set(state):
готово

2023-09-21 16:15 UTC, VasyaLel commented on ui/level_ui/health_indicator/heart.gd
> +			state = State.FULL
готово

2023-09-21 16:42 UTC, Blobson approved these changes

2023-09-22 10:45 UTC, Svedmit approved these changes

2023-09-22 11:15 UTC, merged