#116 List of procuct and prices in shop
Blobson/break-a-leg pull request #143
Opened 2023-10-19 14:37 UTC by Svedmit

2023-10-19 19:32 UTC, Bartolemy12 submitted a review, later dismissed

2023-10-20 13:03 UTC, Blobson requested changes

2023-10-20 13:03 UTC, Blobson commented on ui/menu/phone_menu/shop/products_prices.json
> +			"quantity": 0
`quantity` тут зачем?

2023-10-20 13:03 UTC, Blobson commented on ui/menu/phone_menu/shop/products_prices.json
> +				"level": 0,
`level` не нужен - он совпадает с индексом этого элемента в списке.

2023-10-20 13:03 UTC, Blobson commented on ui/menu/phone_menu/shop/products_prices.json
> +				"price": 0
`price` - мы будем что-то продавать за 0 ?

2023-10-20 13:03 UTC, Blobson commented on ui/menu/phone_menu/shop/products_prices.json
> +			"name": "standart",
Этот скин есть у игрока по-умолчанию, зачем его описание тут?

2023-10-20 14:10 UTC, Blobson requested changes

2023-10-20 14:10 UTC, Blobson commented on ui/menu/phone_menu/shop/products_prices.json
> +		"skins": [
табуляцию поправь плиз

2023-10-20 18:35 UTC, Bartolemy12 approved these changes

2023-10-20 18:54 UTC, merged