#208 Reduction of visibility area
Blobson/break-a-leg pull request #227
Opened 2023-11-07 13:40 UTC by Svedmit

2023-11-07 21:20 UTC, Bartolemy12 submitted a review, later dismissed

2023-11-08 10:05 UTC, Blobson requested changes

2023-11-08 10:05 UTC, Blobson commented on regions/residential_region/level.tscn
> +position = Vector2(0, 108)
Это стоит менять в `base_level.tscn`

2023-11-08 10:29 UTC, Blobson submitted a review, later dismissed

2023-11-08 13:11 UTC, closed without merging