#193 Delivery points + #197 Delivery pointer
Blobson/break-a-leg pull request #235
Opened 2023-11-11 21:12 UTC by Blobson

/closes #193 
/closes #197

2023-11-11 21:24 UTC, Bartolemy12 approved these changes

2023-11-11 23:11 UTC, Svedmit requested changes
Ботинки летают между тайлами, так и должно быть?

2023-11-12 09:32 UTC, Blobson commented
> Ботинки летают между тайлами, так и должно быть?

Исправил.

2023-11-12 15:44 UTC, Svedmit approved these changes

2023-11-12 16:19 UTC, merged