#118 Ability buttons
Blobson/break-a-leg pull request #236
Opened 2023-11-12 20:33 UTC by Svedmit

2023-11-12 21:53 UTC, Bartolemy12 approved these changes

2023-11-12 22:38 UTC, Blobson requested changes

2023-11-12 22:38 UTC, Blobson commented on ui/level_ui/ability_buttons/shield_button.gd
> +class_name HookAbilityButton
Может всё же `ShieldButton`?

2023-11-12 22:38 UTC, Blobson commented on ui/level_ui/ability_buttons/Circle.png
Если не против, давай заменим на вот это:
![ability_progress](https://github.com/Blobson/break-a-leg/assets/2709384/f5abd0a7-c47f-4d09-8e92-9a141be6ddc2)

2023-11-12 22:38 UTC, Blobson commented on ui/level_ui/ability_buttons/shield_button.gd
> +signal shield_button_pressed()
Сигналы я бы перенёс в Game, так как искать в дереве сцены кнопку, чтобы приконнектится к этому сигналу будет довольно неудобно. 
Ну и я бы сигнал назвал `shield_activate` или `shield_activated`, так как обработчику сигнала не обязательно знать что активация произошла именно через нажатие кнопки.

2023-11-12 22:38 UTC, Blobson commented on ui/level_ui/ability_buttons/hook_button.gd
> +signal hook_ability_over()
Данный сигнал не используется и по названию не ясно, что именно планируется с ним делать?
Может добавим описание?

2023-11-13 17:57 UTC, Blobson commented on ui/level_ui/ability_buttons/Circle.png
Нет, всё же твой вариант выглядит лучше. Оставляем как есть.

2023-11-13 18:25 UTC, Blobson commented
![ability_progress](https://github.com/Blobson/break-a-leg/assets/2709384/cd8cee99-bee4-4b0a-8de5-3e62381af0bf)

2023-11-13 19:42 UTC, Blobson approved these changes

2023-11-13 20:36 UTC, Bartolemy12 approved these changes

2023-11-13 21:04 UTC, merged