#249 Broken windows
Blobson/break-a-leg pull request #250
Opened 2023-12-02 11:33 UTC by Svedmit

Add broken windows animation,
Improvement windows generation on tile map
/closes #249

2023-12-02 14:58 UTC, Blobson requested changes

2023-12-02 20:43 UTC, Svedmit commented on regions/residential_region/static_obstacles/window/window_small.tscn
> +resource_name = "broken_3"
косяк, исправлю

2023-12-02 20:51 UTC, Svedmit commented on utils/level_generator/tile_generator.gd
> +		if randi_range(0, 8) == 0:
Речь о выходе окон за здание? я запустил уровень около 15 раз ни разу такого не произошло, меня больше смущает полоса на 2 тайла на краю здания, котрая иногда генериться. для этого у меня была симметрия. либо ее вернуть либо еще идея есть, но надо обсудить

2023-12-03 16:50 UTC, Blobson approved these changes

2023-12-03 16:50 UTC, merged