#177 Прикрутить анимацию нанесения урона цветком курьеру
Blobson/break-a-leg pull request #253
Opened 2023-12-03 20:39 UTC by Bartolemy12

2023-12-03 21:28 UTC, Blobson requested changes

2023-12-03 21:28 UTC, Blobson commented on regions/common/base_static_obstacle/base_static_obstacle.gd
> +
Это нужное изменение?

2023-12-03 21:28 UTC, Blobson commented on regions/residential_region/static_obstacles/biting_plant/biting_plant.gd
> +		$AnimationPlayer.play('turn_right', 0.5, 0.5, true)
А почему мы тут поворачиваемся направо?

2023-12-03 21:28 UTC, Blobson commented on regions/residential_region/static_obstacles/biting_plant/biting_plant.gd
> +#		$Sprite2D.flip_h = body.global_position.x > global_position.x
Этот закомментированный код нужен?

2023-12-05 09:39 UTC, Svedmit approved these changes

2023-12-05 18:25 UTC, Blobson approved these changes

2023-12-05 18:25 UTC, merged