#314 Health loss visual effect
Blobson/break-a-leg pull request #372
Opened 2024-02-07 15:24 UTC by Svedmit

/closes #314

2024-02-07 20:11 UTC, Bartolemy12 submitted a review, later dismissed

2024-02-08 11:56 UTC, Blobson requested changes

2024-02-08 11:56 UTC, Blobson commented on utils/level_generator/level_generator.gd
> +	var top_floor = floor(view_rect.position.y / float(ts.y)) -4
Этого делать не стоит. Нужно понять как это правильно пофиксить.

2024-02-08 11:56 UTC, Blobson commented on characters/courier/courier.tscn
> +[node name="HeartLoss" type="CPUParticles2D" parent="." index="12"]
По хорошему надо бы поместить этот эмиттер за спрайт курьера иначе неестественно выглядит.

2024-02-09 10:04 UTC, Svedmit commented on characters/courier/courier.tscn
> +[node name="HeartLoss" type="CPUParticles2D" parent="." index="12"]
Исправлено

2024-02-09 10:15 UTC, Bartolemy12 approved these changes

2024-02-09 14:32 UTC, Blobson approved these changes

2024-02-09 14:32 UTC, merged