#318 Wall tile color modulate
Blobson/break-a-leg pull request #374
Opened 2024-02-09 14:26 UTC by Svedmit

/close #318

2024-02-09 14:44 UTC, Blobson requested changes

2024-02-09 14:44 UTC, Blobson commented on model/region.gd
> +var wall_colors: Array[Vector4] = []
Здесь можно удалить.

2024-02-09 14:44 UTC, Blobson commented on regions/residential_region/tiles/building_tile_set.tres
> +[sub_resource type="ShaderMaterial" id="ShaderMaterial_62m03"]
Я так понимаю, это больше не нужно.

2024-02-09 14:44 UTC, Blobson commented on tests/delivery_test.tscn
> +modulate = Color(0.729412, 0.721569, 0.780392, 1)
Это лучше сбросить.

2024-02-09 14:44 UTC, Blobson commented on tests/delivery_test.tscn
> +[node name="Sprite2D" type="Sprite2D" parent="."]
А это нужно?

2024-02-09 17:59 UTC, Svedmit commented on tests/delivery_test.tscn
> +modulate = Color(0.729412, 0.721569, 0.780392, 1)
Точно, пропустил этот момент

2024-02-11 21:39 UTC, Blobson approved these changes

2024-02-11 21:39 UTC, merged