#322 Игровое меню (пауза, настройка звука и т.п.)
Blobson/break-a-leg pull request #378
Opened 2024-02-10 21:32 UTC by Bartolemy12

/closes #322

2024-02-11 11:28 UTC, Svedmit commented on ui/level_ui/pause_menu/pause_menu.gd
> +	print(effects_slider_current_value)
Это нужно здесь?

2024-02-11 11:30 UTC, Svedmit commented on regions/common/base_level/base_level.gd
> +	get_tree().quit()
Я думал здесь должен быть возврат в меню, а не выход из игры...

2024-02-11 11:36 UTC, Svedmit commented on regions/common/base_level/base_level.gd
> +	$PauseMenu/SelectButtonBack.finished.connect(resume_the_game)
Такие вещи в глобальном контексте делать опасно, т.к. много кто может использовать этот сигнал. Я бы конектил этот сигнал в обработке нажатия на кнопку. 
p.s. у меня это тоже сделано не правильно, можешь и там заодно поправить :))

2024-02-11 11:39 UTC, Svedmit commented on ui/level_ui/pause_menu/pause_menu.tscn
> +[node name="MusicSoundButton" type="TextureButton" parent="MarginContainer/VBoxContainer/MusicSlider"]
мне не нравится что кнопка "вылезает", думаю что будет лучше если слайдер будет чуть меньше, но список будет ровным.

2024-02-11 11:42 UTC, Svedmit commented
Мне категрически не нравится кнопка настроек в левом верхнем углу UI, считаю это нужно переделать. возможные варианты - правый верхний угол (перенеся индикацию влево) либо под/над индикатором сердечек, чтоб не бросалась в глаза можно модулировать прозрачность кнопки, если на нее не нажимают, чтоб внимание не отвлекала.

2024-02-11 21:48 UTC, Bartolemy12 commented on regions/common/base_level/base_level.gd
> +	get_tree().quit()
с Вовой договаривались на выход из игры вообще :)
Можно добавить 3 кнопку MainMenu

2024-02-11 22:15 UTC, Bartolemy12 commented on ui/level_ui/pause_menu/pause_menu.gd
> +	print(effects_slider_current_value)
Исправлено :)

2024-02-11 22:23 UTC, Bartolemy12 commented on regions/common/base_level/base_level.gd
> +	$PauseMenu/SelectButtonBack.finished.connect(resume_the_game)
Если ты про 23 строку- то вот что происходит если использовать так, как ты пишешь, я пытался избежать этого, и пока так..... :)
![IompkuAEweU](https://github.com/Blobson/break-a-leg/assets/127960590/2e0f9d75-3afc-41a9-ad8c-dda829f6d344)

2024-02-11 22:26 UTC, Bartolemy12 commented on ui/level_ui/pause_menu/pause_menu.tscn
> +[node name="MusicSoundButton" type="TextureButton" parent="MarginContainer/VBoxContainer/MusicSlider"]
Честно говоря я думал об этом, давай обсудим это на собрании :)

2024-02-12 08:41 UTC, Svedmit commented on regions/common/base_level/base_level.gd
> +	get_tree().quit()
Как то странно - выход из игры существует только здесь...

2024-02-15 08:09 UTC, Svedmit commented on regions/common/base_level/base_level.gd
> +	tween.tween_property(self, "scale", Vector2(70, 70), 0.5)
Это точно нужно? выглядит очень странно.

2024-02-15 08:09 UTC, Svedmit commented on ui/level_ui/pause_button/pause_button_3.png
А зачем эти текстуры?

2024-02-15 12:17 UTC, Blobson commented on regions/common/base_level/base_level.gd
> +	tween.tween_property(self, "scale", Vector2(70, 70), 0.5)
Согласен, кажется ненужная история.

2024-02-15 13:01 UTC, Blobson requested changes

2024-02-16 15:54 UTC, Blobson requested changes

2024-02-16 15:54 UTC, Blobson commented on game.gd
> +	get_tree().paused = false
Здесь точно этому не место.

2024-02-16 19:55 UTC, Blobson approved these changes

2024-02-16 19:55 UTC, merged