#5 Глобальный объект GameState
Blobson/break-a-leg pull request #45
Opened 2023-07-27 06:38 UTC by Svedmit

2023-07-27 07:29 UTC, Blobson commented
Надо бы сделать ребейз.

2023-07-27 08:12 UTC, Bartolemy12 approved these changes

2023-07-27 08:29 UTC, Bartolemy12 submitted a review, later dismissed

2023-07-27 18:19 UTC, Bartolemy12 approved these changes

2023-07-27 21:03 UTC, Blobson requested changes

2023-07-27 21:03 UTC, Blobson commented on utils/game_state/game_state.gd
> +signal coin_changed(from, to)
`coins_changed` иначе получается, что поменялся номинал монетки или её разменяли.
И надо определится `..._changed` или `..._updated` иначе непонятно, почему `rating_updated` а `coins_changed`.

2023-07-27 21:50 UTC, Svedmit commented on utils/game_state/game_state.gd
> +signal coin_changed(from, to)
Поправлю. Просто рейтинг изменен звучит как-то странно. сделаю все updated

2023-07-27 21:50 UTC, Svedmit commented on utils/game_state/game_state.gd
> +var coin: int = 0 :
Справедливо

2023-07-28 09:14 UTC, Bartolemy12 approved these changes

2023-07-29 08:53 UTC, Blobson submitted a review, later dismissed

2023-07-29 11:03 UTC, Bartolemy12 approved these changes

2023-07-30 09:42 UTC, Blobson approved these changes

2023-07-30 10:04 UTC, Bartolemy12 approved these changes

2023-07-30 10:10 UTC, merged