#7 Объект камеры
Blobson/break-a-leg pull request #47
Opened 2023-07-27 09:21 UTC by Bartolemy12

2023-07-27 15:24 UTC, Blobson requested changes

2023-07-27 15:24 UTC, Blobson commented on utils/camera/camera_2d.tscn
Почитай, пожалуйста, [вот это](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html).

2023-07-31 15:29 UTC, Blobson requested changes

2023-07-31 15:29 UTC, Blobson commented on utils/camera/camera_2d.gd
> +var width = ProjectSettings.get_setting('display/window/size/width')
Ты проверял значения width и height?
Пробовал их распечатать в `_on_resized()`?

2023-07-31 15:29 UTC, Blobson commented on utils/camera/camera_2d.gd
> +	var delta_width = max(0, current_width - width)
Кажется тут лучше обойтись без `max`.

2023-08-05 12:37 UTC, Blobson approved these changes

2023-08-05 12:38 UTC, Blobson approved these changes

2023-08-05 12:53 UTC, VasyaLel approved these changes

2023-08-05 13:24 UTC, merged