BaseStaticObstacle
Blobson/break-a-leg pull request #48
Opened 2023-07-27 15:55 UTC by VasyaLel

2023-07-27 18:05 UTC, Svedmit approved these changes

2023-07-27 18:24 UTC, Bartolemy12 submitted a review, later dismissed

2023-07-27 20:57 UTC, Blobson requested changes

2023-07-27 20:57 UTC, Blobson commented on regions/common/base_static_obstacle/BaseStaticObstacle.gd
> +	if $AnimationPlayer.has_animation("Activate"):
Давайте тогда уж все анимации называть маленькими буквами, чтобы расхождений не было, а то `idle` и `Activate` - как-то странно выглядит.

2023-07-28 07:32 UTC, VasyaLel commented on regions/common/base_static_obstacle/BaseStaticObstacle.gd
> +	if $AnimationPlayer.has_animation("Activate"):
согласен, поправил

2023-07-28 07:56 UTC, Blobson approved these changes

2023-07-28 09:13 UTC, Bartolemy12 approved these changes

2023-07-28 10:41 UTC, merged