#16 Одинарное окно
Blobson/break-a-leg pull request #51
Opened 2023-08-08 08:08 UTC by Bartolemy12

2023-08-08 09:43 UTC, DemitrSpb submitted a review, later dismissed

2023-08-08 10:31 UTC, Svedmit reviewed
Я все-таки считаю что нужно добавлять тайлы окон в **уже существующий** набор тайлов в ноду examples. Разделить их по слоям или по z-индексу. В таком случае внутри набора можно будет задать id и имя в меню "Набор тайлов". В дальнейшем это поможет избежать путаницы при написании генератора. 
![Безымянный](https://github.com/Blobson/break-a-leg/assets/127945929/d133dee6-4c45-44f9-886d-a93c533f7cba)

2023-08-09 06:58 UTC, Blobson requested changes

2023-08-09 06:58 UTC, Blobson commented on regions/industrial_region/one_window_examples.tscn
А зачем нужен этот TileMap?

2023-08-09 06:58 UTC, Blobson commented on regions/industrial_region/tile_map/one_window_examples.tscn
А этот зачем?

2023-08-09 06:58 UTC, Blobson commented on regions/residential_region/test_level/test_level.tscn
> +[ext_resource type="PackedScene" uid="uid://lrflwu2ehhqb" path="res://regions/industrial_region/one_window_examples.tscn" id="2_xeadx"]
Зачем этот TileMap - мы же договорились, что всё будет в одном тайлмэпе. Генератор не будет создавать десять тайлмепов - всё будет в одном.

2023-08-09 12:57 UTC, Blobson requested changes

2023-08-09 12:57 UTC, Blobson commented on regions/industrial_region/tile_map/one_window_examples.tscn
Зачем нужен этот файл?

2023-08-09 14:38 UTC, Blobson submitted a review, later dismissed

2023-08-10 07:58 UTC, Blobson submitted a review, later dismissed

2023-08-10 08:15 UTC, VasyaLel requested changes

2023-08-10 08:25 UTC, Blobson approved these changes

2023-08-10 08:56 UTC, VasyaLel approved these changes

2023-08-10 11:05 UTC, merged