#43 Damage mechanic
Blobson/break-a-leg pull request #54
Opened 2023-08-11 10:31 UTC by Svedmit

2023-08-11 13:28 UTC, Bartolemy12 submitted a review, later dismissed

2023-08-11 14:42 UTC, VasyaLel approved these changes

2023-08-12 09:31 UTC, Blobson requested changes

2023-08-12 09:31 UTC, Blobson commented on characters/common/base_character/character.gd
> +			Game.health_updated.emit(health, value)
Тут лучше сначала делать присвоение `health = value` а потом уже выстреливать сигнал, иначе можно словить где-нибудь странный эффект. Представь что ты где-то обрабатываешь этот сигнал и там читаешь значение жизней через `get_character().health` - у тебя будет старое значение жизней, а ты будешь думать что оно актуально.
Я тут делаю нехорошее допущение, что ты берешь значение не из параметров сигнала, но всё же...

2023-08-12 09:31 UTC, Blobson commented on characters/common/base_character/character.gd
> +func jump():
Давайте это дело назовём как-то иначе, чтобы не путать с прыжком вперёд на ускорителе.
Например `parachute_jump()`.

2023-08-12 09:31 UTC, Blobson commented on utils/game_state/game_state.gd
> +func getCharacter() -> Character:
Согласно [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) имена функций должны быть в snake_case.

2023-08-14 12:03 UTC, Blobson approved these changes

2023-08-14 12:06 UTC, VasyaLel approved these changes

2023-08-14 12:06 UTC, merged

2023-08-14 12:07 UTC, Bartolemy12 approved these changes