#72 Упорядочить файлы
Blobson/break-a-leg pull request #74
Opened 2023-08-16 10:20 UTC by Bartolemy12

2023-08-16 10:53 UTC, Svedmit approved these changes

2023-08-16 18:45 UTC, DemitrSpb approved these changes

2023-08-17 09:45 UTC, Svedmit submitted a review, later dismissed

2023-08-17 12:44 UTC, Blobson commented on regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_small_2.png
и то же самое с `thorny_plant_small_1.png`

2023-08-17 16:37 UTC, Blobson requested changes

2023-08-17 16:37 UTC, Blobson commented on regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_2.png.import
> +source_file="res://regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_small_2.png"
тут не поправил

2023-08-17 16:37 UTC, Blobson commented on regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_2.png.import
> +source_file="res://regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_small_2.png"
и так везде

2023-08-17 16:37 UTC, Blobson commented on regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_2.png.import
> +source_file="res://regions/residential_region/static_obstacles/thorny_plant_2/thorny_plant_small_2.png"
Мой совет, закрой редактор и удали эти import файлы. Потом открой редактор и они пересоздадутся.

2023-08-17 17:32 UTC, Blobson approved these changes

2023-08-17 21:38 UTC, Svedmit approved these changes

2023-08-18 07:21 UTC, merged