#41 Перемещение персонажа
Blobson/break-a-leg pull request #75
Opened 2023-08-16 12:37 UTC by Svedmit

2023-08-16 16:36 UTC, Bartolemy12 submitted a review, later dismissed

2023-08-17 07:37 UTC, Blobson requested changes

2023-08-17 07:37 UTC, Blobson commented on characters/common/base_character/character.gd
> +	velocity.y = -move_speed
По идее скорость можно задать один раз, например в `_ready()`

2023-08-17 07:37 UTC, Blobson commented on characters/common/base_character/character.gd
> +		animation.play("left")
А где после завершения анимации `left` происходит переход к анимации бега вверх?

2023-08-17 09:09 UTC, Svedmit commented on characters/common/base_character/character.gd
> +		animation.play("left")
В настройках анимаций переходы

2023-08-17 09:10 UTC, Svedmit commented on characters/common/base_character/character.gd
> +func _input(event):
исправлю

2023-08-17 12:45 UTC, Blobson commented on characters/common/base_character/character.gd
> +	velocity.y = -move_speed
ну или после старта уровня.

2023-08-18 10:10 UTC, Bartolemy12 approved these changes

2023-08-18 17:49 UTC, Blobson requested changes

2023-08-18 17:49 UTC, Blobson commented on characters/common/base_character/character.gd
> +func _on_swipe(type):
Мне кажется, что тут немного переусложнено - можно обойтись без сигналов и этого обработчика. Надо будет это обсудить.

2023-08-18 19:22 UTC, Svedmit commented on characters/common/base_character/character.gd
> +func _on_swipe(type):
Я это сделал для того чтоб не пихать в функцию обработки свайпов и анимацию и твины. Так может с точки зрения программы сложнее, но с точки зрения функциональности и понимания - проще

2023-08-19 11:13 UTC, Blobson commented on characters/common/base_character/character.gd
> +func _on_swipe(type):
Нет, я именно про сигналы. Зачем они тут?

2023-08-20 09:04 UTC, Svedmit commented on characters/common/base_character/character.gd
> +func _on_swipe(type):
Исправил

2023-08-20 09:10 UTC, Bartolemy12 approved these changes

2023-08-21 07:40 UTC, Blobson approved these changes

2023-08-21 15:48 UTC, Blobson approved these changes

2023-08-21 19:27 UTC, Blobson submitted a review, later dismissed

2023-08-21 19:28 UTC, VasyaLel submitted a review, later dismissed

2023-08-21 19:31 UTC, Blobson approved these changes

2023-08-21 19:35 UTC, Blobson approved these changes

2023-08-21 19:37 UTC, VasyaLel approved these changes

2023-08-21 19:37 UTC, merged