#33 Dev: Ботинок летящий вниз
Blobson/break-a-leg pull request #77
Opened 2023-08-17 12:31 UTC by Bartolemy12

2023-08-17 12:59 UTC, Blobson requested changes

2023-08-17 12:59 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe/falling_shoe.gd
> +	$Area2D.body_entered.connect(_on_body_entered)
Это уже делается в  классе родителя BaseStaticObstacle. Здесь можно просто вызвать метод родителя через `super()`.

2023-08-17 12:59 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe/falling_shoe.gd
> +func _on_body_entered(body: Node):
Этот метод также есть в классе родителя и он уже содержит всё, кроме `self.queue_free()`. 
Так, что можно переделать на:
```
func _on_body_entered(body: Node):
    super()
    queue_free()
```

2023-08-17 12:59 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe/falling_shoe.gd
> +func _on_body_entered(body: Node):
Заметь, что `queue_free()` - это тоже самое что и `self.queue_free()`.

2023-08-17 12:59 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe/falling_shoe.gd
> +func _on_body_entered(body: Node):
Ещё, хотелось бы, чтобы при ударе о курьера ботинок не исчезал а отлетал в сторону, но это отдельный момент и можно сделать позже.

2023-08-17 17:34 UTC, Blobson approved these changes

2023-08-18 12:34 UTC, Svedmit approved these changes

2023-08-18 17:42 UTC, Blobson approved these changes

2023-08-18 17:50 UTC, merged