#34 Сборка карты вручную
Blobson/break-a-leg pull request #82
Opened 2023-08-22 12:17 UTC by Svedmit

2023-08-22 18:57 UTC, Blobson requested changes

2023-08-22 18:57 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe_4/falling_shoe_4.tscn
> +[node name="PathFollow2D" parent="." index="0"]
Ты уверен что это изменение нужно в сборке карты?

2023-08-23 18:12 UTC, Blobson approved these changes

2023-08-23 19:43 UTC, Bartolemy12 approved these changes

2023-08-23 20:36 UTC, VasyaLel approved these changes

2023-08-23 20:36 UTC, merged