#31 Dev: Цветок в горшке летящий вниз
Blobson/break-a-leg pull request #83
Opened 2023-08-22 12:22 UTC by Bartolemy12

2023-08-22 18:59 UTC, Blobson requested changes

2023-08-23 18:06 UTC, Blobson requested changes

2023-08-23 18:08 UTC, Blobson requested changes

2023-08-23 18:08 UTC, Blobson commented on regions/common/base_dynamic_obstacle/base_falling_object/falling_object.gd
Либо `base_falling_object` либо `falling_object` - ты уж определись ;) Иначе все будут путаться.

2023-08-23 18:10 UTC, Blobson requested changes

2023-08-23 18:10 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/falling_shoe_base_scene/falling_shoe.gd
Пустые скрипты мы удаляем - скриптов в игре и так хватает.

2023-08-24 11:54 UTC, Blobson requested changes

2023-08-24 11:54 UTC, Blobson commented on regions/common/base_dynamic_obstacle/base_falling_object/base_falling_object.gd
Класс надо называть в соответствии с названием файла, т.е. для `base_falling_object.gd` это `BaseFallingObject`

2023-08-30 13:10 UTC, Blobson submitted a review, later dismissed

2023-08-30 19:56 UTC, Svedmit approved these changes

2023-08-30 20:02 UTC, Blobson approved these changes

2023-08-31 11:18 UTC, Svedmit approved these changes

2023-08-31 22:14 UTC, merged