бабка с ковриком
Blobson/break-a-leg pull request #87
Opened 2023-08-25 21:03 UTC by VasyaLel

добавил бабку, вынес код поворота объекта в сторону игрока в общий базовый объект и добавил свойство flippable (будет поворачиваться в сторону игрока если включено, но нужно чтобы объект изначально был направлен влево)

2023-08-25 21:11 UTC, Blobson requested changes

2023-08-25 21:11 UTC, Blobson commented on regions/common/base_static_obstacle/base_static_obstacle.gd
> +	var obstacle_position = $'.'.global_transform.origin.x
Тут не нужно `$'.'` перед `global_transform`. 
Достаточно:
```
var obstacle_position = global_transform.origin.x
```

2023-08-25 21:11 UTC, Blobson commented on regions/common/base_static_obstacle/base_static_obstacle.gd
> +	var courier_position_x = body.get_global_position().x
Вместо `body.get_global_transform()` можно писать `body.global_transform`

2023-08-25 21:35 UTC, VasyaLel commented on regions/common/base_static_obstacle/base_static_obstacle.gd
> +	var obstacle_position = $'.'.global_transform.origin.x
упростил _deploy_to_target()

2023-08-25 21:35 UTC, VasyaLel commented on regions/common/base_static_obstacle/base_static_obstacle.gd
> +	var courier_position_x = body.get_global_position().x
упростил _deploy_to_target()

2023-08-25 21:45 UTC, Blobson approved these changes

2023-08-26 10:02 UTC, Svedmit approved these changes

2023-08-26 12:48 UTC, Bartolemy12 approved these changes

2023-08-27 10:44 UTC, merged