#29 Dev: Птицы летающие по горизонтали (вороны, сороки или голуби)
Blobson/break-a-leg pull request #88
Opened 2023-08-27 20:50 UTC by Bartolemy12

2023-08-28 08:37 UTC, Blobson requested changes

2023-08-28 08:37 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +class_name FliyngBird extends BaseDynamicObstacle
Очепятка в слове `flying`.

2023-08-28 08:41 UTC, Blobson requested changes

2023-08-28 08:41 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +@onready var curve = $"../..".get_curve()
Вот тут я не понял, зачем тут `$"../.."`?

2023-08-28 08:41 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +	if $Sprite2D.get_global_position() == curve.get_point_position(2):
Это условие окончания пути? Если да, то надо переделать.

2023-08-30 20:06 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +@onready var curve = $"../..".get_curve()
Почему просто не привязать скрипт к узлу `FlyingBirdBaseScene` ?

2023-08-30 20:07 UTC, Blobson requested changes

2023-08-30 20:07 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +	$Sprite2D.flip_h = true
Поворот спрайта надо определять по направлению движения, а не задавать константой.

2023-08-30 20:27 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +	$Sprite2D.flip_h = true
Например так:
```
func _ready():
    $Sprite2D.flip_h = _get_sprite_flip()
    super()
    
func _physics_process(delta):
    $Sprite2D.flip_h = _get_sprite_flip()
    super(delta)

func _get_sprite_flip():
    transform = curve.sample_baked_with_rotation(path_follow.offset)
    return transform.y.x > 0
```

2023-08-30 20:28 UTC, Blobson commented on regions/residential_region/dynamic_obstacles/flying_birds_base_scene/flying_birds.gd
> +@onready var curve = $"../..".get_curve()
Ага, похоже это косяк на уровне `BaseDynamicObstacle` - надо будет это исправить.

2023-09-02 09:05 UTC, Blobson submitted a review, later dismissed

2023-09-02 10:38 UTC, Blobson approved these changes

2023-09-02 20:49 UTC, DemitrSpb approved these changes

2023-09-02 22:58 UTC, merged